# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bbRJp1KzIil_F2zGJDIfIyjJ8fLZJeEI

Projeto: Simulação de Conta Bancária em Python
Desenvolva um programa que simule uma conta bancária simples, atendendo aos seguintes
requisitos:
1. O usuário deve iniciar com um saldo inicial de R$1000,00.
2. O sistema deve permitir as seguintes operações:
Consultar saldo
Sacar dinheiro (com verificação de saldo suficiente)
3. O programa deve utilizar uma estrutura de repetição while para manter o sistema
em execução contínua.
4. O usuário deve ter a opção de encerrar o programa quando desejar.
5. O sistema deve apresentar um menu de opções para interação com o usuário.
6. O programa deve tratar entradas inválidas de forma adequada (por exemplo, opções
inexistentes ou valores negativos).
"""

saldo = 1000
historico = []

while True:
    print("1-Ver saldo 2-Depositar 3-Sacar 4-Sair")
    opc = input("Escolha: ")

    if opc == "1":
        print(f"Saldo: R$ {saldo}")
        print("Histórico:", historico if historico else "Nenhuma operação")

    elif opc == "2":
        v = float(input("Valor: R$ "))
        if v > 0:
            saldo += v
            historico.append(f"Depósito R$ {v}")
        else:
            print("Valor inválido!")

    elif opc == "3":
        v = float(input("Valor: R$ "))
        if v <= 0:
            print("Valor inválido!")
        elif v > saldo:
            print("Saldo insuficiente!")
        elif v > 800:
            print("Limite de saque: R$800")
        else:
            saldo -= v
            historico.append(f"Saque R$ {v}")

    elif opc == "4":
        break

    else:
        print("Opção inválida!")